const div = document.querySelector('div');
const para = document.createElement('p');

let x = 5;

document.write(typeof(x));
document.write(" ");
document.write(800 + "85");
document.write(" ");
document.write(0/0);
document.write(" ");
document.write(isNaN("string"));
document.write(" ");
document.write(isNaN(69));
document.write(" ");
document.write(2E310);
document.write(" ");
document.write(-2E310);
document.write(" ");
document.write(5 > 4);
document.write(" ");
document.write(5 < 4);
console.log("Math with console.log function");
console.log(4 + 4);
console.log("equality (non-type-specific) false");
console.log(4 == 5);
console.log("equality (non-type-specific) true");
console.log(4 == 4);
console.log("equality (type-specific) true");
console.log(4 === 4);
console.log("equality (type-specific) false");
console.log(4 === "5");
console.log("equality (type-specific) false");
console.log(4 === "4");
console.log("equality (type-specific) false");
console.log(4 === 5);
console.log("OR output true");
console.log(4<5 || 4 == 5);
console.log("OR output false");
console.log(4>5 || 4 == 5);
console.log("NOT operator output false");
console.log(!(true));
console.log("NOT operator output true");
console.log(!(false));